import Head from 'next/head';
import { Box, Flex, Text } from '@chakra-ui/react';
import { DataTable, Sidemenu } from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          {/* サイドメニュー */}
          {/* <Sidemenu /> */}
          {/* メインコンテンツ */}
          <Box bg="white" color="blue" width="100px" height="100px">
            <h1 color="red">title</h1>
            <Text color="red">Text</Text>
          </Box>
      </div>
    </>
  );
}
